#!/usr/bin/env bash
#
# build-plugins.sh — Build all Cloudstream plugins and collect artifacts
#
# Runs the Gradle build, then copies .cs3 files and plugins.json to the
# specified output directory.
#
# Usage:
#   build-plugins.sh <output-dir>
#
# Exit codes:
#   0  Success
#   1  Build failure or missing artifacts
#

set -euo pipefail

readonly OUTPUT_DIR="${1:?Usage: $0 <output-dir>}"

log()   { printf '%s\n' "$*"; }
error() { printf '::error::%s\n' "$*" >&2; }

main() {
  if [[ ! -d "$OUTPUT_DIR" ]]; then
    error "Output directory does not exist: $OUTPUT_DIR"
    exit 1
  fi

  if [[ ! -f gradlew ]]; then
    error "gradlew not found — run this script from the project root"
    exit 1
  fi

  if ! ./gradlew make makePluginsJson --parallel --build-cache --no-daemon; then
    error "Gradle build failed"
    exit 1
  fi

  # Collect .cs3 plugin files
  shopt -s nullglob globstar
  local -a cs3_files=(**/build/*.cs3)

  if [[ ${#cs3_files[@]} -eq 0 ]]; then
    error "No .cs3 files were produced by the build"
    exit 1
  fi

  cp "${cs3_files[@]}" "$OUTPUT_DIR"
  log "Copied ${#cs3_files[@]} plugin files"

  # Collect plugins.json manifest
  if [[ ! -f build/plugins.json ]]; then
    error "plugins.json was not generated by the build"
    exit 1
  fi

  cp build/plugins.json "$OUTPUT_DIR"
  log "Copied plugins.json"
}

main
